# Generated by Django 5.0.1 on 2024-01-07 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0002_alter_user_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
