# Generated by Django 5.0.1 on 2024-01-07 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0006_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ("-id",)},
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="pcover_picture",
            new_name="cover_picture",
        ),
    ]
