# Generated by Django 5.0.1 on 2024-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0007_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_line2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
