# Generated by Django 5.0.1 on 2024-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0008_profile_address_line2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/cover_pictures"
            ),
        ),
    ]
