# Generated by Django 5.0.1 on 2024-01-07 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0009_alter_profile_cover_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="latlongitude",
            new_name="longitude",
        ),
    ]
