# Generated by Django 5.0.1 on 2024-01-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0010_rename_latlongitude_profile_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("vendor", "Vendor"), ("customer", "Customer")],
                max_length=10,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
